import type { Metadata } from "next";
import "./styles/reset/reset.scss";
import Menu from "./repetitiveComponents/menu/menu";
import Footer from "./repetitiveComponents/footer/footer";
import MobileMenu from "./repetitiveComponents/mobileMenu";

export const metadata: Metadata = {
  title: "NEXSOL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Menu />
        <MobileMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
